# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=3002

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Install Gunicorn
RUN pip install gunicorn

# Expose port 3002 for Gunicorn
EXPOSE 3002

# Use Gunicorn as the entry point to run your application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:3002", "app:app"]
